/* Phares des côtes de France — sélection emblématique.
   rank 0 : visibles dès la vue nationale ; 1 : zoom régional ; 2 : zoom local.
   sea : true = phare en mer. h : hauteur (m), year : mise en service. */
"use strict";

const PHARES = [
  // Mer du Nord & Manche est
  { id: "risban", name: "Phare de Dunkerque (Risban)", lat: 51.0510, lon: 2.3660, dep: "Nord (59)", h: 63, year: 1843, rank: 1, txt: "Le phare le plus septentrional de France, en plein port de Dunkerque." },
  { id: "calais-ph", name: "Phare de Calais", lat: 50.9578, lon: 1.8552, dep: "Pas-de-Calais (62)", year: 1848, rank: 2, txt: "Tour blanche octogonale au cœur de la ville ; on y grimpe pour voir l'Angleterre par temps clair." },
  { id: "gris-nez", name: "Phare du cap Gris-Nez", lat: 50.8687, lon: 1.5850, dep: "Pas-de-Calais (62)", rank: 0, txt: "Au point de France le plus proche de l'Angleterre (34 km) ; veille sur le détroit le plus fréquenté du monde." },
  { id: "alprech", name: "Phare d'Alprech", lat: 50.6990, lon: 1.5673, dep: "Pas-de-Calais (62)", rank: 2, txt: "Signale l'approche sud de Boulogne-sur-Mer, premier port de pêche de France." },
  { id: "carnot", name: "Phare de la digue Carnot", lat: 50.7406, lon: 1.5676, sea: true, dep: "Pas-de-Calais (62)", rank: 2, txt: "Au bout des 3 200 m de la digue Carnot, il commande l'entrée de Boulogne-sur-Mer, premier port de pêche de France." },
  { id: "touquet", name: "Phare du Touquet", lat: 50.5240, lon: 1.5900, dep: "Pas-de-Calais (62)", rank: 2, txt: "Tour de brique reconstruite en 1951 ; domine la baie de Canche et la forêt du Touquet." },
  { id: "berck", name: "Phare de Berck", lat: 50.3983, lon: 1.5608, dep: "Pas-de-Calais (62)", rank: 2, txt: "Reconstruit après-guerre au-dessus des dunes ; il éclaire l'entrée de l'Authie et la longue plage de Berck." },
  { id: "cayeux", name: "Phare de Cayeux-sur-Mer", lat: 50.1943, lon: 1.5121, dep: "Somme (80)", rank: 2, txt: "Rouge et blanc au-dessus des galets, il garde l'entrée sud de la baie de Somme." },
  { id: "ault", name: "Phare d'Ault", lat: 50.1055, lon: 1.4542, dep: "Somme (80)", year: 1951, rank: 2, txt: "En pleine ville, sur la falaise d'Onival : sa lanterne domine la mer de près de 110 m, là où les falaises de craie viennent mourir dans la baie de Somme." },
  { id: "ailly", name: "Phare d'Ailly", lat: 49.9099, lon: 0.9548, dep: "Seine-Maritime (76)", rank: 2, txt: "Troisième phare du site, au sommet des falaises de craie du pays de Caux, près de Varengeville." },
  { id: "antifer", name: "Phare d'Antifer", lat: 49.6902, lon: 0.1657, dep: "Seine-Maritime (76)", rank: 2, txt: "Reconstruit après-guerre au-dessus des falaises, entre Étretat et Le Havre." },
  { id: "la-heve", name: "Phare de la Hève", lat: 49.5077, lon: 0.0690, dep: "Seine-Maritime (76)", rank: 2, txt: "Béton et hublots d'après-guerre ; domine l'entrée du port du Havre depuis le cap." },
  // Baie de Seine (Calvados)
  { id: "ouistreham", name: "Phare de Ouistreham", lat: 49.2796, lon: -0.2473, dep: "Calvados (14)", year: 1905, rank: 2, txt: "Tour de pierre et brique à l'entrée du canal de Caen à la mer, au-dessus de Sword Beach ; l'un des rares phares de la côte à avoir traversé 1944 debout." },
  { id: "ver-sur-mer", name: "Phare de Ver-sur-Mer", lat: 49.3401, lon: -0.5189, dep: "Calvados (14)", rank: 2, txt: "Sa tour blanche à couronne rouge domine Gold Beach ; endommagé en 1944, remis en état après la Libération, il servit aussi de radiophare." },
  // Manche ouest / Cotentin
  { id: "gatteville", name: "Phare de Gatteville", lat: 49.6947, lon: -1.2653, dep: "Manche (50)", h: 75, year: 1835, rank: 0, txt: "Deuxième plus haut phare de France en pierre ; 365 fenêtres, autant que de jours. Il garde le raz de Barfleur." },
  { id: "cap-levi", name: "Phare du cap Lévi", lat: 49.6960, lon: -1.4700, dep: "Manche (50)", rank: 2, txt: "Tour carrée de granit rose reconstruite en 1947, à l'est de Cherbourg." },
  { id: "fort-ouest", name: "Phare du fort de l'Ouest", lat: 49.6743, lon: -1.6478, sea: true, dep: "Manche (50)", rank: 2, txt: "Planté sur le fort qui garde la passe ouest de la plus grande rade artificielle du monde, à Cherbourg." },
  { id: "goury", name: "Phare de Goury (la Hague)", lat: 49.7183, lon: -1.9483, sea: true, dep: "Manche (50)", rank: 1, txt: "Sur son rocher face au nez de Jobourg, il veille sur le raz Blanchard, l'un des courants les plus violents d'Europe." },
  { id: "carteret-ph", name: "Phare de Carteret", lat: 49.3715, lon: -1.8085, dep: "Manche (50)", rank: 2, txt: "Sur le cap, au départ du sentier des douaniers ; vue sur les îles Anglo-Normandes." },
  { id: "granville-ph", name: "Phare de la pointe du Roc", lat: 48.8350, lon: -1.6136, dep: "Manche (50)", year: 1828, rank: 2, txt: "À la pointe de la cité corsaire de Granville, face à Chausey." },
  { id: "chausey", name: "Phare de Chausey", lat: 48.8695, lon: -1.8224, sea: true, dep: "Manche (50)", rank: 2, txt: "Sur la Grande Île de l'archipel de Chausey, au milieu d'un dédale d'îlots que découvrent les plus fortes marées d'Europe." },
  // Bretagne nord
  { id: "frehel", name: "Phare du cap Fréhel", lat: 48.6852, lon: -2.3190, dep: "Côtes-d'Armor (22)", year: 1950, rank: 0, txt: "Au sommet de falaises de grès rose de 70 m, l'un des plus beaux panoramas de Bretagne nord." },
  { id: "heaux", name: "Phare des Héaux de Bréhat", lat: 48.9125, lon: -3.0886, sea: true, year: 1840, dep: "Côtes-d'Armor (22)", rank: 1, txt: "Chef-d'œuvre de Léonce Reynaud posé en pleine mer sur les récifs, au large de l'archipel de Bréhat." },
  { id: "ploumanach", name: "Phare de Mean Ruz (Ploumanac'h)", lat: 48.8305, lon: -3.4890, dep: "Côtes-d'Armor (22)", rank: 1, txt: "Tout en granit rose, reconstruit après 1944 ; gardien du chaos rocheux de Ploumanac'h." },
  { id: "sept-iles", name: "Phare des Sept-Îles", lat: 48.8788, lon: -3.4715, sea: true, dep: "Côtes-d'Armor (22)", rank: 2, txt: "Sur l'île aux Moines, au cœur de la plus grande réserve d'oiseaux marins de France (fous de Bassan, macareux)." },
  { id: "batz", name: "Phare de l'île de Batz", lat: 48.7448, lon: -4.0248, dep: "Finistère (29)", rank: 2, txt: "Domine l'île face à Roscoff ; 198 marches et une vue sur toute la côte du Léon." },
  { id: "ile-vierge", name: "Phare de l'île Vierge", lat: 48.6403, lon: -4.5670, sea: true, h: 82.5, year: 1902, dep: "Finistère (29)", rank: 0, txt: "Le plus haut phare d'Europe en pierre de taille ; son escalier est tapissé de 12 500 plaques d'opaline." },
  { id: "le-four", name: "Phare du Four", lat: 48.5230, lon: -4.8043, sea: true, dep: "Finistère (29)", rank: 1, txt: "Dans le chenal du Four ; les photos de tempête où la vague l'engloutit ont fait le tour du monde." },
  // Ouessant & Iroise
  { id: "stiff", name: "Phare du Stiff (Ouessant)", lat: 48.4744, lon: -5.0567, year: 1695, dep: "Finistère (29)", rank: 1, txt: "Construit sous Vauban : l'un des plus anciens phares de France encore en service." },
  { id: "creach", name: "Phare du Créac'h (Ouessant)", lat: 48.4592, lon: -5.1289, h: 55, year: 1863, dep: "Finistère (29)", rank: 0, txt: "L'un des phares les plus puissants du monde : il ouvre l'entrée de la Manche. Musée des Phares et Balises à son pied." },
  { id: "jument", name: "Phare de la Jument", lat: 48.4222, lon: -5.1339, sea: true, year: 1911, dep: "Finistère (29)", rank: 0, txt: "Rendu mythique par la photo de Jean Guichard (1989) : le gardien sur le seuil, la vague derrière." },
  { id: "kereon", name: "Phare de Kéréon", lat: 48.4372, lon: -5.0256, sea: true, year: 1916, dep: "Finistère (29)", rank: 1, txt: "Le « palace des phares » : boiseries et parquet marqueté. Dernier phare en mer gardienné de France (2004)." },
  { id: "saint-mathieu", name: "Phare de Saint-Mathieu", lat: 48.3302, lon: -4.7702, dep: "Finistère (29)", rank: 0, txt: "Dressé dans les ruines d'une abbaye médiévale, face à la mer d'Iroise." },
  { id: "petit-minou", name: "Phare du Petit Minou", lat: 48.3374, lon: -4.6169, dep: "Finistère (29)", rank: 1, txt: "Avec son pont de pierre, il aligne l'entrée du goulet de Brest ; l'un des plus photographiés de France." },
  { id: "ar-men", name: "Phare d'Ar-Men", lat: 48.0503, lon: -4.9990, sea: true, year: 1881, dep: "Finistère (29)", rank: 0, txt: "« L'Enfer des Enfers » : le plus exposé des phares français, au bout de la chaussée de Sein. 14 ans de chantier." },
  { id: "la-vieille", name: "Phare de la Vieille", lat: 48.0402, lon: -4.7565, sea: true, dep: "Finistère (29)", rank: 1, txt: "Face à la pointe du Raz, il tient tête aux courants du raz de Sein." },
  { id: "eckmuhl", name: "Phare d'Eckmühl", lat: 47.7979, lon: -4.3726, h: 65, year: 1897, dep: "Finistère (29)", rank: 0, txt: "Granit gris et escalier d'opaline, financé par la fille du maréchal Davout, prince d'Eckmühl." },
  // Bretagne sud & Loire
  { id: "goulphar", name: "Grand Phare de Goulphar (Belle-Île)", lat: 47.3086, lon: -3.2184, year: 1836, dep: "Morbihan (56)", rank: 1, txt: "Domine les aiguilles de Port-Coton peintes par Monet." },
  { id: "poulains", name: "Phare des Poulains (Belle-Île)", lat: 47.3874, lon: -3.2532, dep: "Morbihan (56)", rank: 2, txt: "Sur sa presqu'île qui s'isole à marée haute ; Sarah Bernhardt vécut à côté." },
  { id: "port-navalo", name: "Phare de Port-Navalo", lat: 47.5490, lon: -2.9180, dep: "Morbihan (56)", rank: 2, txt: "Marque l'entrée du golfe du Morbihan et de ses courants." },
  { id: "pilier", name: "Phare du Pilier", lat: 47.0428, lon: -2.3565, sea: true, dep: "Loire-Atlantique (44)", rank: 2, txt: "Deux tours jumelles sur l'île du Pilier, au large de Noirmoutier." },
  // Atlantique
  { id: "baleines", name: "Phare des Baleines (Ré)", lat: 46.2486, lon: -1.5614, year: 1854, dep: "Charente-Maritime (17)", rank: 0, txt: "À la pointe nord-ouest de l'île de Ré ; 257 marches et la vieille tour Vauban à ses côtés." },
  { id: "chassiron", name: "Phare de Chassiron (Oléron)", lat: 46.0472, lon: -1.4106, year: 1836, dep: "Charente-Maritime (17)", rank: 1, txt: "Zébré noir et blanc à la pointe nord d'Oléron ; jardins dessinés en rose des vents." },
  { id: "coubre", name: "Phare de la Coubre", lat: 45.6953, lon: -1.2397, h: 64, year: 1905, dep: "Charente-Maritime (17)", rank: 1, txt: "Rouge et blanc au-dessus de la Côte Sauvage ; il guide l'entrée de la Gironde." },
  { id: "cordouan", name: "Phare de Cordouan", lat: 45.5867, lon: -1.1735, sea: true, h: 67.5, year: 1611, dep: "Gironde (33)", rank: 0, txt: "Le « roi des phares » : le plus ancien de France en activité, Renaissance en pleine mer, classé UNESCO en 2021." },
  { id: "grave", name: "Phare de Grave", lat: 45.5686, lon: -1.0644, dep: "Gironde (33)", rank: 2, txt: "Face à Cordouan, à la pointe du Médoc ; il abrite un musée des phares." },
  { id: "cap-ferret", name: "Phare du Cap Ferret", lat: 44.6316, lon: -1.2489, year: 1947, dep: "Gironde (33)", rank: 0, txt: "Rouge au-dessus des pins ; vue sur le banc d'Arguin et la dune du Pilat, à l'entrée du Bassin." },
  { id: "contis", name: "Phare de Contis", lat: 44.0957, lon: -1.3190, dep: "Landes (40)", rank: 1, txt: "Seul phare des Landes, spirale noire et blanche au milieu des dunes et de la forêt." },
  { id: "biarritz", name: "Phare de Biarritz", lat: 43.4963, lon: -1.5644, dep: "Pyrénées-Atlantiques (64)", rank: 0, txt: "Pointe Saint-Martin : 248 marches, la Côte basque et les Pyrénées à l'horizon. Il marque la fin des plages landaises." },
  // Méditerranée
  { id: "cap-bear", name: "Phare du cap Béar", lat: 42.5157, lon: 3.1370, dep: "Pyrénées-Orientales (66)", rank: 1, txt: "Marbre rose des Pyrénées au-dessus de la côte Vermeille, près de Port-Vendres." },
  { id: "sete-ph", name: "Phare Saint-Louis (Sète)", lat: 43.3970, lon: 3.7010, dep: "Hérault (34)", rank: 2, txt: "Au bout du môle, il veille sur les joutes et l'entrée du port de Sète." },
  { id: "espiguette", name: "Phare de l'Espiguette", lat: 43.4870, lon: 4.1430, dep: "Gard (30)", rank: 1, txt: "Perdu dans les dunes camarguaises : depuis sa construction, le rivage s'est éloigné de plus de 700 m." },
  { id: "faraman", name: "Phare de Faraman", lat: 43.4088, lon: 4.7318, dep: "Bouches-du-Rhône (13)", rank: 2, txt: "En Camargue, l'érosion a fait l'inverse de l'Espiguette : la mer s'est rapprochée jusqu'à ses pieds." },
  { id: "planier", name: "Phare du Planier", lat: 43.1990, lon: 5.2305, sea: true, year: 1959, dep: "Bouches-du-Rhône (13)", rank: 0, txt: "Sur son île au large de Marseille ; un feu y signale l'approche du port depuis le Moyen Âge." },
  { id: "porquerolles", name: "Phare de Porquerolles", lat: 42.9822, lon: 6.2068, dep: "Var (83)", rank: 1, txt: "Au cap d'Arme, dans le parc national de Port-Cros ; balade emblématique de l'île." },
  { id: "camarat", name: "Phare du cap Camarat", lat: 43.2018, lon: 6.6810, dep: "Var (83)", rank: 2, txt: "Haut perché au-dessus de Pampelonne, l'un des feux les plus élevés de Méditerranée." },
  { id: "garoupe", name: "Phare de la Garoupe (Antibes)", lat: 43.5642, lon: 7.1320, dep: "Alpes-Maritimes (06)", rank: 2, txt: "Sur le plateau de la Garoupe ; par temps clair, la vue court de l'Estérel à l'Italie." },
  { id: "cap-ferrat-ph", name: "Phare du cap Ferrat", lat: 43.6755, lon: 7.3308, dep: "Alpes-Maritimes (06)", rank: 2, txt: "À la pointe de la presqu'île, entre Nice et Monaco." },
  // Corse
  { id: "revellata", name: "Phare de la Revellata", lat: 42.5794, lon: 8.7245, dep: "Haute-Corse (2B)", rank: 2, txt: "Sur sa presqu'île sauvage face à la citadelle de Calvi." },
  { id: "sanguinaires", name: "Phare des Sanguinaires", lat: 41.8830, lon: 8.5960, sea: true, dep: "Corse-du-Sud (2A)", rank: 1, txt: "Sur la Grande Sanguinaire, îles rouges au couchant chantées par Alphonse Daudet." },
  { id: "pertusato", name: "Phare de Pertusato", lat: 41.3700, lon: 9.1830, dep: "Corse-du-Sud (2A)", rank: 0, txt: "Au-dessus des falaises blanches de Bonifacio, le point le plus au sud de la France métropolitaine, face à la Sardaigne." },
  { id: "alistro", name: "Phare d'Alistro", lat: 42.2635, lon: 9.5433, dep: "Haute-Corse (2B)", rank: 2, txt: "Seul grand phare de la plaine orientale corse, entre mer et étangs." },

  // --- Bretagne & Pays de la Loire (livret DIRM NAMO 2025) ---
  { id: "roches-douvres", name: "Phare des Roches-Douvres", lat: 49.105, lon: -2.8139, sea: true, dep: "Côtes-d'Armor (22)", h: 64.6, year: 1954, rank: 1, txt: "Le plus isolé des phares français : à mi-chemin entre Bréhat et Guernesey, en pleine Manche." },
  { id: "triagoz", name: "Phare des Triagoz", lat: 48.87139, lon: -3.64639, sea: true, dep: "Côtes-d'Armor (22)", h: 29.0, year: 1864, rank: 1, txt: "Sur les récifs au nord de la baie de Lannion, face à la côte de granit rose." },
  { id: "rosedo", name: "Phare du Rosédo (Bréhat)", lat: 48.8575, lon: -3.00333, dep: "Côtes-d'Armor (22)", h: 13.0, rank: 2, txt: "Au nord de l'île de Bréhat, il veille sur l'archipel et le chenal du Ferlas." },
  { id: "bodic", name: "Phare de Bodic", lat: 48.8123605, lon: -3.0909294, dep: "Côtes-d'Armor (22)", h: 23.0, year: 1867, rank: 2, txt: "Sur la rive gauche de l'estuaire du Trieux, il guide la remontée vers Lézardrieux." },
  { id: "grand-lejon", name: "Phare du Grand Léjon", lat: 48.74833, lon: -2.66472, sea: true, dep: "Côtes-d'Armor (22)", h: 24.8, rank: 2, txt: "En pleine baie de Saint-Brieuc, à neuf milles au large ; sa tour rouge et blanche est un repère de la baie." },
  { id: "pierre-herpin", name: "Phare de la Pierre de Herpin", lat: 48.729444, lon: -1.815, sea: true, dep: "Ille-et-Vilaine (35)", h: 23.77, year: 1882, rank: 1, txt: "Sentinelle de l'entrée de la baie du Mont-Saint-Michel, au large de la pointe du Grouin ; son embase évasée encaisse les vagues." },
  { id: "roscoff-ph", name: "Phare de Roscoff", lat: 48.7225, lon: -3.98055556, dep: "Finistère (29)", h: 24.4, rank: 2, txt: "Balise l'entrée du port de Roscoff, porte de l'île de Batz et des ferries d'Angleterre." },
  { id: "pontusval", name: "Phare de Pontusval", lat: 48.677938, lon: -4.346478, dep: "Finistère (29)", h: 12.9, year: 1869, rank: 2, txt: "Petite tour carrée posée au milieu des chaos granitiques de Brignogan-Plages." },
  { id: "rochebonne", name: "Phare de Rochebonne", lat: 48.67111, lon: -1.97833, dep: "Ille-et-Vilaine (35)", h: 19.9, year: 1951, rank: 2, txt: "Tour carrée d'après-guerre ; elle forme un alignement avec le Grand Jardin pour entrer à Saint-Malo par la Grande Porte." },
  { id: "grand-jardin", name: "Phare du Grand Jardin", lat: 48.670028, lon: -2.08278, sea: true, dep: "Ille-et-Vilaine (35)", h: 32.7, rank: 1, txt: "Dressé sur un récif devant Saint-Malo, reconstruit après sa destruction en 1944." },
  { id: "la-lande", name: "Phare de la Lande", lat: 48.63694, lon: -3.88528, dep: "Finistère (29)", h: 20.3, rank: 2, txt: "En arrière du littoral léonard, il forme un alignement pour l'approche de Roscoff." },
  { id: "bas-sablons", name: "Phare des Bas-Sablons", lat: 48.636111, lon: -2.021667, dep: "Ille-et-Vilaine (35)", h: 19.5, rank: 2, txt: "À Saint-Servan, en alignement avec le phare de la Balue pour guider l'accès au port de Saint-Malo." },
  { id: "balue", name: "Phare de la Balue", lat: 48.626667, lon: -2.003889, dep: "Ille-et-Vilaine (35)", h: 36.6, year: 1868, rank: 2, txt: "Domine Saint-Servan au sud-est de Saint-Malo ; son feu vert directionnel balise le chenal intérieur." },
  { id: "ile-wrach", name: "Phare de l'île Wrac'h", lat: 48.614722, lon: -4.575833, dep: "Finistère (29)", h: 12.75, year: 1947, rank: 2, txt: "Maison-phare sur l'îlot Wrac'h, à l'entrée de l'Aber-Wrac'h ; désormais lieu de résidence d'artistes." },
  { id: "lanvaon", name: "Phare de Lanvaon", lat: 48.61, lon: -4.53556, dep: "Finistère (29)", h: 27.0, rank: 2, txt: "Feu d'alignement arrière pour l'entrée dans l'Aber-Wrac'h, l'un des mouillages les plus sûrs du Léon." },
  { id: "lanildut", name: "Feu de l'Aber-Ildut (Lanildut)", lat: 48.471119, lon: -4.759188, dep: "Finistère (29)", h: 5.4, rank: 2, txt: "Feu de l'Aber-Ildut, à l'entrée du premier port goémonier d'Europe." },
  { id: "nividic", name: "Phare de Nividic (Ouessant)", lat: 48.4456, lon: -5.1508, sea: true, dep: "Finistère (29)", h: 35.55, rank: 1, txt: "Le plus occidental des phares de France, à la pointe d'Ouessant ; il fut longtemps ravitaillé par téléphérique." },
  { id: "trezien", name: "Phare de Trézien", lat: 48.42361, lon: -4.77889, dep: "Finistère (29)", h: 37.2, year: 1894, rank: 2, txt: "À Plouarzel ; son feu directionnel guide les navires dans le chenal du Four." },
  { id: "kermorvan", name: "Phare de Kermorvan", lat: 48.36194, lon: -4.78972, dep: "Finistère (29)", h: 20.35, rank: 1, txt: "Au Conquet : le phare à terre le plus occidental de France, relié par un isthme étroit." },
  { id: "portzic", name: "Phare du Portzic", lat: 48.3583, lon: -4.53417, dep: "Finistère (29)", h: 58.0, year: 1848, rank: 2, txt: "Sur la rive nord du goulet de Brest, il commande l'entrée de la rade." },
  { id: "pierres-noires", name: "Phare des Pierres Noires", lat: 48.31111111, lon: -4.91444444, sea: true, dep: "Finistère (29)", h: 28.0, year: 1872, rank: 1, txt: "Sur un récif battu au sud-ouest de la mer d'Iroise, à l'entrée du goulet de Brest." },
  { id: "millier", name: "Phare de la pointe du Millier", lat: 48.09861, lon: -4.46556, dep: "Finistère (29)", h: 7.5, year: 1881, rank: 2, txt: "Maison-feu de la pointe du Millier, accrochée au cap Sizun au-dessus de la baie de Douarnenez." },
  { id: "tevennec", name: "Phare de Tévennec", lat: 48.06972, lon: -4.79333, sea: true, dep: "Finistère (29)", h: 15.0, rank: 1, txt: "Dans le raz de Sein, sur un îlot réputé maudit : ses gardiens y devinrent fous, il fut automatisé dès 1910." },
  { id: "goulenez", name: "Grand phare de l'île de Sein (Goulenez)", lat: 48.0367, lon: -4.8494, dep: "Finistère (29)", h: 50.9, year: 1952, rank: 1, txt: "Grand phare de l'île de Sein, reconstruit après-guerre ; il veille sur la chaussée de Sein." },
  { id: "benodet", name: "Phare de Bénodet (la Pyramide)", lat: 47.875, lon: -4.11278, dep: "Finistère (29)", h: 57.0, year: 1887, rank: 2, txt: "Dit « la Pyramide », il forme l'alignement d'entrée de la rivière de l'Odet." },
  { id: "sainte-marine", name: "Phare de Sainte-Marine", lat: 47.8643, lon: -4.11303, dep: "Finistère (29)", h: 20.2, rank: 2, txt: "Maison-feu à l'entrée de l'Odet, face à Bénodet." },
  { id: "moutons", name: "Phare de l'île aux Moutons", lat: 47.77444, lon: -4.0278, sea: true, dep: "Finistère (29)", h: 17.1, rank: 2, txt: "Sur l'île aux Moutons, entre les Glénan et Bénodet, au cœur d'une réserve d'oiseaux marins." },
  { id: "penfret", name: "Phare de Penfret (Glénan)", lat: 47.72111111, lon: -3.95305556, dep: "Finistère (29)", h: 24.25, rank: 2, txt: "Sur la plus orientale des îles de l'archipel des Glénan." },
  { id: "pen-men", name: "Phare de Pen Men (Groix)", lat: 47.6475, lon: -3.509166, dep: "Morbihan (56)", h: 27.6, rank: 1, txt: "À la pointe nord-ouest de l'île de Groix, au-dessus des falaises." },
  { id: "pointe-des-chats", name: "Phare de la pointe des Chats (Groix)", lat: 47.620748, lon: -3.421515, dep: "Morbihan (56)", h: 15.2, year: 1898, rank: 2, txt: "À la pointe sud-est de Groix, dans la réserve géologique ; l'un des phares les plus bas de Bretagne." },
  { id: "penlan", name: "Phare de Penlan", lat: 47.51639, lon: -2.50194, dep: "Morbihan (56)", h: 18.0, year: 1839, rank: 2, txt: "À Billiers, il commande l'entrée de la Vilaine et de son estuaire." },
  { id: "port-maria", name: "Phare de Port-Maria (Quiberon)", lat: 47.479444, lon: -3.124167, dep: "Morbihan (56)", h: 24.8, year: 1895, rank: 2, txt: "Au port de Quiberon, d'où embarquent les navires pour Belle-Île, Houat et Hoëdic." },
  { id: "teignouse", name: "Phare de la Teignouse", lat: 47.4575, lon: -3.04583, sea: true, dep: "Morbihan (56)", h: 20.0, year: 1845, rank: 2, txt: "Dans le passage de la Teignouse, chenal étroit et agité entre Quiberon et Houat." },
  { id: "grands-cardinaux", name: "Phare des Grands Cardinaux", lat: 47.32111, lon: -2.835, sea: true, dep: "Morbihan (56)", h: 27.0, year: 1880, rank: 2, txt: "Sur un récif au large de Hoëdic, il signale les hauts-fonds des Cardinaux." },
  { id: "kerdonis", name: "Phare de Kerdonis (Belle-Île)", lat: 47.31, lon: -3.05944, dep: "Morbihan (56)", h: 13.7, year: 1879, rank: 2, txt: "À la pointe est de Belle-Île, il marque l'entrée sud du golfe du Morbihan." },
  { id: "four-croisic", name: "Phare du plateau du Four (Le Croisic)", lat: 47.29778, lon: -2.63417, sea: true, dep: "Loire-Atlantique (44)", h: 27.1, year: 1945, rank: 2, txt: "Sur le plateau du Four, écueil redouté au large du Croisic." },
  { id: "morees", name: "Phare des Morées", lat: 47.2508, lon: -2.2169, sea: true, dep: "Loire-Atlantique (44)", h: 16.2, rank: 2, txt: "Dans l'estuaire de la Loire, il balise le chenal d'accès à Saint-Nazaire." },
  { id: "aiguillon", name: "Phare d'Aiguillon", lat: 47.24222, lon: -2.26306, dep: "Loire-Atlantique (44)", h: 18.4, rank: 2, txt: "À Saint-Nazaire, il marque l'entrée du port et l'embouchure de la Loire." },
  { id: "grand-charpentier", name: "Phare du Grand Charpentier", lat: 47.21361, lon: -2.31889, sea: true, dep: "Loire-Atlantique (44)", h: 27.3, year: 1945, rank: 2, txt: "Sur un rocher de l'estuaire de la Loire, entre Saint-Nazaire et Pornichet." },
  { id: "banche", name: "Phare de la Banche", lat: 47.177222, lon: -2.4675, sea: true, dep: "Loire-Atlantique (44)", h: 27.6, year: 1865, rank: 2, txt: "À l'ouest de l'embouchure de la Loire, sur le plateau de la Banche." },
  { id: "pointe-saint-gildas", name: "Phare de la pointe Saint-Gildas", lat: 47.133611, lon: -2.245833, dep: "Loire-Atlantique (44)", h: 14.8, rank: 2, txt: "À Préfailles, il garde l'entrée sud de l'estuaire de la Loire." },
  { id: "pointe-des-dames", name: "Phare de la pointe des Dames (Noirmoutier)", lat: 47.0111, lon: -2.22111, dep: "Vendée (85)", h: 18.7, rank: 2, txt: "À la pointe nord-est de Noirmoutier, au-dessus du bois de la Chaise." },
  { id: "fromentine", name: "Phare de Fromentine", lat: 46.891, lon: -2.137, dep: "Vendée (85)", h: 10.0, rank: 2, txt: "À La Barre-de-Monts, face au goulet de Fromentine et au pont de Noirmoutier." },
  { id: "yeu", name: "Grand phare de l'île d'Yeu", lat: 46.7175, lon: -2.38194, dep: "Vendée (85)", h: 37.5, rank: 1, txt: "Grand phare de l'île d'Yeu, reconstruit après 1944 ; sa lanterne domine toute l'île." },
  { id: "corbeaux", name: "Phare de la pointe des Corbeaux (Yeu)", lat: 46.69, lon: -2.285, dep: "Vendée (85)", h: 19.2, rank: 2, txt: "À la pointe sud-est de l'île d'Yeu, au-dessus de la côte sauvage." },
  { id: "barges", name: "Phare des Barges", lat: 46.495, lon: -1.84194, sea: true, dep: "Vendée (85)", h: 31.3, year: 1861, rank: 1, txt: "Sur le rocher des Barges, au large des Sables-d'Olonne, isolé en pleine mer." },
  { id: "armandeche", name: "Phare de l'Armandèche", lat: 46.48972, lon: -1.80472, dep: "Vendée (85)", h: 39.0, rank: 1, txt: "Aux Sables-d'Olonne : l'un des derniers grands phares construits en France, à la silhouette blanche et rouge." },
  { id: "grouin-du-cou", name: "Phare du Grouin du Cou", lat: 46.3444, lon: -1.46361, dep: "Vendée (85)", h: 16.3, year: 1953, rank: 2, txt: "Entre La Tranche-sur-Mer et La Faute, il signale les hauts-fonds du pertuis Breton." },
];
