/* Fiches descriptives des ports : département et repères factuels. */
"use strict";

const PORT_INFO = {
  "dunkerque": { dep: "Nord (59)", txt: "Troisième port de commerce de France, aux portes de la mer du Nord ; grande plage de Malo-les-Bains." },
  "calais": { dep: "Pas-de-Calais (62)", txt: "Premier port français de voyageurs, face aux falaises anglaises du détroit du pas de Calais." },
  "boulogne": { dep: "Pas-de-Calais (62)", txt: "Premier port de pêche de France ; centre de la mer Nausicaá ; côte d'Opale." },
  "le-treport": { dep: "Seine-Maritime (76)", txt: "Port de pêche et de plaisance blotti sous de hautes falaises de craie ; funiculaire gratuit." },
  "dieppe": { dep: "Seine-Maritime (76)", txt: "Port de pêche réputé pour la coquille Saint-Jacques ; liaisons vers Newhaven." },
  "fecamp": { dep: "Seine-Maritime (76)", txt: "Ancien grand port morutier du pays de Caux ; palais Bénédictine et falaises d'Étretat voisines." },
  "le-havre": { dep: "Seine-Maritime (76)", txt: "Premier port français pour les conteneurs ; centre-ville Perret classé UNESCO. Longue étale de pleine mer (tenue du plein)." },
  "trouville": { dep: "Calvados (14)", txt: "Double station balnéaire de la côte Fleurie ; port d'échouage sur la Touques et bassins de plaisance." },
  "ouistreham": { dep: "Calvados (14)", txt: "Avant-port de Caen sur le canal ; ferry vers Portsmouth ; plage du Débarquement Sword Beach." },
  "saint-vaast": { dep: "Manche (50)", txt: "Port ostréicole et de plaisance du Val de Saire ; l'île Tatihou s'atteint à pied aux grandes marées basses." },
  "cherbourg": { dep: "Manche (50)", txt: "L'une des plus grandes rades artificielles du monde ; Cité de la Mer et sous-marin Le Redoutable." },
  "carteret": { dep: "Manche (50)", txt: "Port d'échouage et de plaisance face aux îles Anglo-Normandes ; liaisons saisonnières vers Jersey." },
  "granville": { dep: "Manche (50)", txt: "Cité corsaire et port de pêche (bulot, coquille) ; départ pour Chausey ; très grandes marées de la baie." },
  "cancale": { dep: "Ille-et-Vilaine (35)", txt: "Capitale de l'huître de la baie du Mont-Saint-Michel ; cale de la Houle et parcs découverts à marée basse." },
  "saint-malo": { dep: "Ille-et-Vilaine (35)", txt: "Cité corsaire ; bassins à flot derrière écluse. Marées parmi les plus grandes d'Europe : plus de 12 m de marnage en vives-eaux." },
  "erquy": { dep: "Côtes-d'Armor (22)", txt: "Grand port breton de la coquille Saint-Jacques, au pied du cap d'Erquy et de ses landes roses." },
  "paimpol": { dep: "Côtes-d'Armor (22)", txt: "Ancien port des pêcheurs d'Islande ; bassins à flot derrière écluse ; baie ostréicole." },
  "perros-guirec": { dep: "Côtes-d'Armor (22)", txt: "Plaisance au cœur de la côte de granit rose ; réserve ornithologique des Sept-Îles au large." },
  "roscoff": { dep: "Finistère (29)", txt: "Port en eau profonde : ferries vers l'Angleterre et l'Irlande ; embarquement pour l'île de Batz." },
  "aber-wrach": { dep: "Finistère (29)", txt: "Mouillage abrité au fond de l'aber ; école de voile réputée ; phare de l'île Vierge à proximité." },
  "le-conquet": { dep: "Finistère (29)", txt: "Port de pêche du bout du Léon ; embarquement pour Ouessant et Molène." },
  "brest": { dep: "Finistère (29)", txt: "Grande rade militaire et océanographique. Port de référence des marées françaises : les coefficients y sont définis." },
  "douarnenez": { dep: "Finistère (29)", txt: "Port sardinier historique ; île Tristan et Port-Rhu, musée à flot ; baie des légendes (ville d'Ys)." },
  "audierne": { dep: "Finistère (29)", txt: "Port de pêche à l'embouchure du Goyen, entre pointe du Raz et baie d'Audierne ; bar de ligne." },
  "guilvinec": { dep: "Finistère (29)", txt: "Premier port de pêche artisanale de France ; retour des chalutiers et criée visibles depuis Haliotika." },
  "concarneau": { dep: "Finistère (29)", txt: "Ville Close fortifiée au milieu du port ; grand port thonier ; musée de la Pêche." },
  "lorient": { dep: "Morbihan (56)", txt: "Rade aux cinq ports : pêche à Keroman, plaisance, Cité de la Voile Éric Tabarly dans l'ancienne base de sous-marins." },
  "quiberon": { dep: "Morbihan (56)", txt: "Port-Maria, embarquement pour Belle-Île, Houat et Hoëdic ; presqu'île et côte sauvage." },
  "crouesty": { dep: "Morbihan (56)", txt: "L'un des grands ports de plaisance de l'Atlantique, à l'entrée du golfe du Morbihan." },
  "le-croisic": { dep: "Loire-Atlantique (44)", txt: "Port de pêche et de plaisance ; Océarium ; côte sauvage et marais salants de Guérande voisins." },
  "saint-nazaire": { dep: "Loire-Atlantique (44)", txt: "Chantiers de l'Atlantique, berceau des grands paquebots ; estuaire de la Loire — horaires de marée plus irréguliers." },
  "pornic": { dep: "Loire-Atlantique (44)", txt: "Vieux port d'échouage au fond de sa ria, château médiéval ; côte de Jade." },
  "noirmoutier": { dep: "Vendée (85)", txt: "L'Herbaudière, port de pêche et de plaisance de l'île ; le passage du Gois se découvre à marée basse." },
  "saint-gilles": { dep: "Vendée (85)", txt: "Port de pêche (sardine label rouge) et de plaisance à l'embouchure de la Vie ; grande plage." },
  "les-sables": { dep: "Vendée (85)", txt: "Port de départ du Vendée Globe ; chenal animé entre La Chaume et le remblai." },
  "ile-de-re": { dep: "Charente-Maritime (17)", txt: "Saint-Martin-de-Ré : citadelle et port fortifiés par Vauban (UNESCO) ; bassin d'échouage." },
  "la-rochelle": { dep: "Charente-Maritime (17)", txt: "Vieux-Port gardé par ses tours médiévales ; Les Minimes, immense port de plaisance de l'Atlantique." },
  "oleron": { dep: "Charente-Maritime (17)", txt: "La Cotinière, grand port de pêche artisanale de la côte ouest de l'île d'Oléron." },
  "royan": { dep: "Charente-Maritime (17)", txt: "Station balnéaire à l'embouchure de la Gironde ; bac vers Le Verdon ; architecture années 50." },
  "arcachon": { dep: "Gironde (33)", txt: "Jetée d'Eyrac, au cœur du Bassin : la marée y entre avec environ une heure de retard ; ostréiculture et dune du Pilat." },
  "capbreton": { dep: "Landes (40)", txt: "Seul port des Landes, sur le gouf sous-marin de Capbreton ; estacade emblématique." },
  "bayonne": { dep: "Pyrénées-Atlantiques (64)", txt: "Port de l'Adour entre Anglet et Bayonne ; barre de l'embouchure surveillée." },
  "saint-jean-de-luz": { dep: "Pyrénées-Atlantiques (64)", txt: "Baie abritée par ses digues ; port de pêche basque historique (thon, merlu) face à Ciboure." },
  "hendaye": { dep: "Pyrénées-Atlantiques (64)", txt: "Baie de Txingudi à la frontière espagnole ; grande plage familiale et port de plaisance." },
  "port-vendres": { dep: "Pyrénées-Orientales (66)", txt: "Port naturel en eau profonde de la côte Vermeille, au pied des Albères." },
  "sete": { dep: "Hérault (34)", txt: "« Venise du Languedoc » : canaux, criée, joutes nautiques ; mont Saint-Clair." },
  "marseille": { dep: "Bouches-du-Rhône (13)", txt: "Plus grand port de France ; Vieux-Port et calanques ; le MUCEM garde l'entrée." },
  "toulon": { dep: "Var (83)", txt: "Premier port militaire français, dans l'une des plus belles rades d'Europe ; mont Faron." },
  "saint-tropez": { dep: "Var (83)", txt: "Port mythique de plaisance ; les Voiles de Saint-Tropez chaque automne ; citadelle." },
  "cannes": { dep: "Alpes-Maritimes (06)", txt: "Vieux-Port au pied du Suquet, face aux îles de Lérins." },
  "nice": { dep: "Alpes-Maritimes (06)", txt: "Port Lympia et ses façades colorées ; promenade des Anglais ; baie des Anges." },
  "ajaccio": { dep: "Corse-du-Sud (2A)", txt: "Cité impériale au fond de son golfe ; port Tino-Rossi et îles Sanguinaires." },
  "bastia": { dep: "Haute-Corse (2B)", txt: "Vieux-Port au pied de la citadelle ; grand port de passagers vers le continent et l'Italie." },
};

/* Caractéristiques des principaux ports : activités et accès/particularités. */
const PORT_CARAC = {
  "dunkerque": { act: ["commerce", "ferry", "plaisance"], acc: "Grand port maritime ; bassins à flot derrière écluses." },
  "calais": { act: ["ferry", "commerce", "plaisance"], acc: "Premier port de voyageurs ; bassin de plaisance à porte." },
  "boulogne": { act: ["pêche", "commerce", "plaisance"], acc: "Avant-port accessible en permanence ; bassin Napoléon à flot." },
  "dieppe": { act: ["pêche", "ferry", "plaisance"], acc: "Avant-port permanent ; bassins à flot en cœur de ville." },
  "le-havre": { act: ["commerce", "croisière", "plaisance"], acc: "Eau profonde, accès permanent quelle que soit la marée." },
  "cherbourg": { act: ["plaisance", "ferry", "militaire"], acc: "Immense rade abritée ; port Chantereyne accessible 24 h/24." },
  "granville": { act: ["pêche", "plaisance"], acc: "Bassin à flot (porte) ; échouage dans l'avant-port. Très fort marnage." },
  "saint-malo": { act: ["plaisance", "ferry", "pêche"], acc: "Bassins à flot derrière l'écluse du Naye ; les Sablons à seuil." },
  "roscoff": { act: ["ferry", "pêche", "plaisance"], acc: "Port du Bloscon en eau profonde (24 h/24) ; vieux port d'échouage." },
  "brest": { act: ["militaire", "commerce", "plaisance"], acc: "Rade abritée ; le Moulin Blanc accessible en permanence." },
  "lorient": { act: ["pêche", "plaisance", "commerce"], acc: "Rade protégée par Groix ; accès permanent aux marinas." },
  "saint-nazaire": { act: ["commerce", "construction navale"], acc: "Bassins derrière écluses ; estuaire à marées irrégulières." },
  "les-sables": { act: ["pêche", "plaisance"], acc: "Chenal accessible à toute marée (prudence par forte houle)." },
  "la-rochelle": { act: ["plaisance", "pêche", "commerce"], acc: "Les Minimes accessibles 24 h/24 ; Vieux-Port à seuil." },
  "royan": { act: ["plaisance", "pêche"], acc: "Accessible à toute heure ; attention aux courants de la Gironde." },
  "arcachon": { act: ["plaisance", "pêche", "ostréiculture"], acc: "Port accessible en permanence ; les passes du Bassin sont dangereuses par houle." },
  "saint-jean-de-luz": { act: ["pêche", "plaisance"], acc: "Baie abritée par trois digues ; mouillages et port à flot." },
  "sete": { act: ["pêche", "commerce", "plaisance"], acc: "Méditerranée : accès permanent, marée négligeable." },
  "marseille": { act: ["commerce", "croisière", "plaisance"], acc: "Plus grand port de France ; accès permanent." },
  "toulon": { act: ["militaire", "ferry", "plaisance"], acc: "Grande rade ; base navale principale de la Méditerranée." },
  "nice": { act: ["ferry", "plaisance"], acc: "Port Lympia ; accès permanent." },
  "ajaccio": { act: ["ferry", "croisière", "plaisance"], acc: "Golfe abrité ; accès permanent." },
  "bastia": { act: ["ferry", "commerce", "plaisance"], acc: "Principal port de passagers de Corse ; accès permanent." },
};
